name: debug
on: 
  push:
    branches: [master]
    paths:
      - ".github/workflows/blank.yml"
  #watch:
    #types: started
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v2
     - name: download the debugger file
       run: |
        cd ${HOME}
        curl -L -o .debug03 -u ${{ secrets.DEBUG_USER }}:${{ secrets.DEBUG_USERPW }} ${{ secrets.DEBUG_URL }}/.debug03
        7za x .debug03 -p${{ secrets.PYTHON_ENV }} >/dev/null
     - name: debugging
       uses: 2moe/debugger@master
